// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package sqlc

import (
	"database/sql"
	"time"
)

type Book struct {
	BookID        int32          `json:"book_id"`
	CollectionID  int32          `json:"collection_id"`
	Title         sql.NullString `json:"title"`
	Author        sql.NullString `json:"author"`
	Language      sql.NullString `json:"language"`
	YearPublished sql.NullInt32  `json:"year_published"`
	Isbn          sql.NullString `json:"isbn"`
	CreatedAt     time.Time      `json:"created_at"`
}

type Collection struct {
	CollectionID int32          `json:"collection_id"`
	User         string         `json:"user"`
	Name         sql.NullString `json:"name"`
	Status       sql.NullInt32  `json:"status"`
	CreatedAt    time.Time      `json:"created_at"`
}

type User struct {
	Username  string         `json:"username"`
	Role      sql.NullString `json:"role"`
	CreatedAt time.Time      `json:"created_at"`
}
