// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package sqlc

import (
	"database/sql"
)

type Book struct {
	BookID        int32
	CollectionID  sql.NullInt32
	Title         sql.NullString
	Author        sql.NullString
	Language      sql.NullString
	YearPublished sql.NullInt32
	Isbn          sql.NullString
	CreatedAt     sql.NullTime
}

type Collection struct {
	CollectionID int32
	UserID       sql.NullInt32
	Name         sql.NullString
	Status       sql.NullInt32
	CreatedAt    sql.NullTime
}

type User struct {
	ID        int32
	Username  sql.NullString
	Role      sql.NullString
	CreatedAt sql.NullTime
}
