// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package sqlc

import (
	"database/sql"
)

type Book struct {
	BookID        int32          `json:"book_id"`
	CollectionID  sql.NullInt32  `json:"collection_id"`
	Title         sql.NullString `json:"title"`
	Author        sql.NullString `json:"author"`
	Language      sql.NullString `json:"language"`
	YearPublished sql.NullInt32  `json:"year_published"`
	Isbn          sql.NullString `json:"isbn"`
	CreatedAt     sql.NullTime   `json:"created_at"`
}

type Collection struct {
	CollectionID int32          `json:"collection_id"`
	UserID       sql.NullInt32  `json:"user_id"`
	Name         sql.NullString `json:"name"`
	Status       sql.NullInt32  `json:"status"`
	CreatedAt    sql.NullTime   `json:"created_at"`
}

type User struct {
	ID        int32          `json:"id"`
	Username  sql.NullString `json:"username"`
	Role      sql.NullString `json:"role"`
	CreatedAt sql.NullTime   `json:"created_at"`
}
